name: Download, Unzip, and Rename File

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  download_process_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download IMDB Ratings File
      run: |
        curl -L -o ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz

    - name: Unzip the file
      run: |
        gunzip ratings.tsv.gz

    - name: Rename the file
      run: |
        mv ratings.tsv ratings.txt
