name: Download, Unzip, and Rename File

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


jobs:
  process_file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download file
      run: |
        curl -L -o ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz

    - name: Unzip file
      run: |
        gunzip ratings.tsv.gz

    - name: Rename file
      run: |
        mv ratings.tsv ratings.txt
