name: Process and Store IMDB Ratings File

on:
  schedule:
    - cron: '9 11 29 * *'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows the workflow to commit and push changes

jobs:
  download_process_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download IMDB Ratings File
      run: |
        curl -L -o ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz

    - name: Unzip the file
      run: |
        gunzip ratings.tsv.gz

    - name: Rename the file
      run: |
        mv ratings.tsv ratings.txt

    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ratings.txt
        git commit -m "Update IMDB ratings" || echo "No changes to commit"
        git push
