name: Process and Store IMDB Ratings File

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows the workflow to commit and push changes

jobs:
  download_process_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download IMDB Ratings File
      run: |
        curl -L -o ratings.tsv.gz https://datasets.imdbws.com/title.ratings.tsv.gz

    - name: Unzip the file
      run: |
        gunzip ratings.tsv.gz

    - name: Rename the file to .txt
      run: |
        mv ratings.tsv ratings.txt

    - name: Convert .tsv to .csv
      run: |
        awk 'BEGIN {FS="\t"; OFS=","}
             NR == 1 {
               # Split the header, quote each part, and join with commas
               n = split($0, headers, FS);
               header_line = "";
               for (i = 1; i <= n; i++) {
                 header_line = header_line "\"" headers[i] "\"";
                 if (i < n) header_line = header_line OFS;
               }
               print header_line;
             }
             NR > 1 {
               # Convert tabs to commas and ensure existing commas within fields are preserved
               gsub(FS, OFS, $0);
               print;
             }' ratings.txt > ratings.csv


    - name: Commit and push changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ratings.csv
        git commit -m "Update and convert IMDB ratings to CSV format"
        git push
